### PR TITLE
Fix intermittent failure in CPU test

### LINKED ISSUE #104: Intermittent failure in one output of CPU inference
```
Starting tests of model xgboost-cpu without visible GPU...
Performance statistics for xgboost-cpu:
Random seed value: 111245
Traceback (most recent call last):
  File "/triton_fil/qa/L0_e2e/test_model.py", line 608, in <module>
    run_test(
  File "/triton_fil/qa/L0_e2e/test_model.py", line 483, in run_test
    np.testing.assert_almost_equal(
  File "/root/miniconda3/envs/triton_test/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 583, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/root/miniconda3/envs/triton_test/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1046, in assert_array_almost_equal
    assert_array_compare(compare, x, y, err_msg=err_msg, verbose=verbose,
  File "/root/miniconda3/envs/triton_test/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 3 decimals
Mismatched elements: 1 / 128 (0.781%)
Max absolute difference: 2.
Max relative difference: 1.
 x: array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,...
 y: array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,...
```

We might want to loosen up the test slightly by allowing a small percentage of failures in classification output for CPU vs GPU evaluation. @hcho3 any thoughts on what makes sense here?

### PR DESCRIPTION
**Pull request by hcho3**
Closes #104

### CODE REVIEW

**Comment by wphicks** [comment]
I'm not sure we just want to switch everything over to `predict_proba` since we want to explicitly exercise the code paths and configurations for both class output and probability output. No need to rush a fix since this is an extremely intermittent issue; let's just follow the strategy used in cuML and demand that 99% (or pick your threshold) of class outputs match. Alternatively (and maybe even better), we could compare directly to a local run of GTIL rather than FIL in order to (theoretically) guarantee a match.

**Comment by hcho3** [comment]
@wphicks I was quite nervous about allowing a mismatch in class outputs, because then we can't differentiate between tiny difference (49.6% vs 50.4%) and significant difference (80% vs 20%). However, running GTIL locally seems like a reasonable path.

**Comment by hcho3** [comment]
As it turns out, running GTIL inside `test_model.py` is proving to be quite tricky. This is because how the flags differ between FIL (`predict_proba`) and GTIL (`pred_transform`). The difference is resolved with sophisticated glue logic in `src/gtil_utils.cu`, but it's hard to do that in a Python script.

For now, let's settle with checking 99% match in the class outputs. In the long term, we should add a new API to Treelite that exposes the `predict_proba` flag that behaves the same way as `predict_proba` in FIL.

**Comment by wphicks** [comment]
@hcho3 If you approve of #115, I think we should be able to close this in favor of that, right?

**Comment by hcho3** [comment]
Closing in favor of #115

**Pull request closed without merging**
