### PR TITLE
Apply changes to CMake configuration

### PR DESCRIPTION
**Pull request by mc-nv**

### CODE REVIEW

**Comment by wphicks** [comment]
@mc-nv, I'm assuming that this is a follow up to #371 because it did not solve your problem? I'm fine with the cmake minimum version change, but can you help me understand why the project declaration needs to be moved outside of the if/else branch as we [discussed](https://github.com/triton-inference-server/fil_backend/pull/371#discussion_r1438767329) on #371?

**Comment by mc-nv** [comment]
> @mc-nv, I'm assuming that this is a follow up to #371 because it did not solve your problem? I'm fine with the cmake minimum version change, but can you help me understand why the project declaration needs to be moved outside of the if/else branch as we [discussed](https://github.com/triton-inference-server/fil_backend/pull/371#discussion_r1438767329) on #371?

Previous commit has a `CMakeLists.txt` constraint where minimal required version must be declared as [top-level instruction](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html).
> **Note** Call the `cmake_minimum_required()` command at the beginning of the top-level CMakeLists.txt file even before calling the [project()](https://cmake.org/cmake/help/latest/command/project.html#command:project) command. It is important to establish version and policy settings before invoking other commands whose behavior they may affect. See also policy [CMP0000](https://cmake.org/cmake/help/latest/policy/CMP0000.html#policy:CMP0000).

Regarding removing `project()` command, I simply follow the book approach where according to [documentation](https://cmake.org/cmake/help/latest/command/enable_language.html#command:enable_language) this approach is more elegant IMO. 
> Enables support for the named languages in CMake. This is the same as the [project()](https://cmake.org/cmake/help/latest/command/project.html#command:project) command but does not create any of the extra variables that are created by the project command.

**Comment by wphicks** [comment]
> Previous commit has a CMakeLists.txt constraint where minimal required version must be declared as [top-level instruction](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html).

The real issue here is that our CMakeLists.txt is really two CMakeLists.txt files stacked on top of one another for convenience. It would be useful not to have to constrain the CMake version to something so recent if we're just going to invoke the build through Docker, but once we're working with the actual bare-metal build, we need 3.26.4. The guidance on when to call `cmake_minimum_required` is generally correct, but we should interpret that as calling it at the top of each branch of the if/else.

Practically, this is a concern because RAPIDS is almost always at one of the most recent CMake versions, but it would be preferable not to always impose that condition on Triton.

As for the project declaration, I'm not too opinionated on it either way. I slightly prefer the separate project declarations because it emphasizes the above idea that these are really two different build configs, but `enable_language` works just fine too.

**Comment by mc-nv** [comment]
@wphicks  we are happy with any solution that will solve compilation process for Triton. 

We can come back to https://github.com/triton-inference-server/fil_backend/pull/372 changes if that's what you willing to see.

**Comment by wphicks** [comment]
> we are happy with any solution that will solve compilation process for Triton

Of course! That's number one priority, and I'm happy to get a temporary solution in and then clean up if necessary with further discussion. Could you file an [issue](https://github.com/triton-inference-server/fil_backend/issues/new) with a reproducer for the problem you're seeing so we can track both the initial solution and any necessary follow-up? I want to make sure that any subsequent clean-up we do does not re-introduce the problem, and I'm not entirely sure what the problem is at the moment.

**Comment by wphicks** [comment]
Sorry, @mc-nv, forgot to tag you in the above.

**Comment by Tabrizian** [comment]
@wphicks Sorry, it was probably my fault for putting the previous PR for review before making sure it fixed the issue in our CI (the original version did, but after applying reviews it didn't). All we need is just a minimum CMake version in the docker build branch to get the build passing.

**Comment by wphicks** [comment]
@Tabrizian Great! Thanks very much for the context. Could you go ahead and post an issue with reproducer now? I'm 100% okay with merging a fix that just gets CI green again, but I want to make sure I understand the issue. CMake's `project` command has supported `VERSION` since 3.0.2 at least (and maybe earlier), so after we get CI green, I'd like to investigate further.

For now, I can't confirm that this change gets CI green, since build.py builds are blocked by the current problem with fetching boost. Our other build path does not reproduce the issue.

**Comment by Tabrizian** [comment]
Let's get this merged: https://github.com/triton-inference-server/fil_backend/pull/372

Green pipeline: https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/jobs/78848045

I'm going to file a reproducer for this issue to make sure it is covered in CI for future changes.

**Comment by wphicks** [comment]
Accidentally merged this one, but reverted and merged #372. Thanks, @Tabrizian!

**Pull request merged**
