### PR TITLE
Add support for Treelite binary checkpoint model format

### LINKED ISSUE #17: Generic method to (de)serialize Treelite handle
Related: https://github.com/wphicks/triton_fil_backend/pull/6#discussion_r614369156

Currently, it is not possible to (de)serialize a Treelite handle. Consequently, you'd need to load cuML RF and sklearn tree models as Python objects. We do not want to add Python dependency to Triton.

Proposal: Add a generic method to (de)serialize a Treelite handle. The handle can represent any of the tree models that Treelite currently supports. This way, we can achieve a good separation between Treelite (which loads the model) and Triton (which consumes the model). The data flow is as follows:

1. Treelite loads cuML RF or sklearn tree model (Python objects). Treelite is able to construct a C++ object in memory.
2. Treelite serializes the C++ model object.
3. Triton deserializes the C++ model object.
4. Triton performs inference with the model.

Posting this issue here, since I don't think we want to reference this repo in Treelite's issue tracker yet.

### PR DESCRIPTION
**Pull request by hcho3**
Closes #17.

Try this example with sklearn `RandomForestRegressor`:

1. Train a  `RandomForestRegressor` with 100 trees and save it as a Python pickle:
```python
import time
import ctypes
import numpy as np
from sklearn.datasets import make_regression
from sklearn.ensemble import RandomForestRegressor
import pickle

X, y = make_regression(n_samples=100000, n_features=100, n_informative=100)
clf = RandomForestRegressor(n_estimators=100, n_jobs=-1)
clf.fit(X, y)

with open('model.pkl', 'wb') as f:
    pickle.dump(clf, f)
```

2. Convert the sklearn model into a Treelite binary checkpoint by running
```
python -m treelite.serialize --input-model ./model.pkl --input-model-type sklearn_pkl  \
    --output-checkpoint checkpoint.tl
```
Now you can use `checkpoint.tl` in the FIL backend.

3. Use the following configuration in `config.pbtxt`. Notice that we now set `model_type` to `treelite_checkpoint`.
```
name: "fil"
backend: "fil"
max_batch_size: 1048576
input [
 {
    name: "input__0"
    data_type: TYPE_FP32
    dims: [ 100 ]
  }
]
output [
 {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]
instance_group [{ kind: KIND_GPU }]
parameters [
  {
    key: "model_type"
    value: { string_value: "treelite_checkpoint" }
  },
  {
    key: "predict_proba"
    value: { string_value: "false" }
  },
  {
    key: "output_class"
    value: { string_value: "false" }
  },
  {
    key: "algo"
    value: { string_value: "ALGO_AUTO" }
  },
  {
    key: "storage_type"
    value: { string_value: "AUTO" }
  },
  {
    key: "blocks_per_sm"
    value: { string_value: "0" }
  }
]

dynamic_batching {
  preferred_batch_size: [1, 2, 4, 8, 16, 32, 64, 128, 1024, 131072, 1048576]
  max_queue_delay_microseconds: 30000
}
```

4. Now start the server (see the command in the front page README).
5. You now should be able to submit requests with the Triton client:
```python
import numpy as np
import tritonclient.http as triton_http

http_client = triton_http.InferenceServerClient(
    url='localhost:8000',
    verbose=False,
    concurrency=12
)

# Generate dummy data to classify
features = 100
samples = 10000
rng = np.random.default_rng(seed=0)
data = rng.random(size=(samples, features), dtype='float32')

triton_input_http = triton_http.InferInput(
    'input__0',
    (samples, features),
    'FP32'
)
triton_input_http.set_data_from_numpy(data, binary_data=True)
triton_output_http = triton_http.InferRequestedOutput(
    'output__0',
    binary_data=True
)

request_http = http_client.infer(
    'fil',
    model_version='1',
    inputs=[triton_input_http],
    outputs=[triton_output_http]
)

result_http = request_http.as_numpy('output__0')
```

### CODE REVIEW

**Comment by hcho3** [comment]
To test this PR, I will need to build cuML and Treelite from the source inside the Triton Docker container, since there isn't yet a new version of Treelite released and cuML is currently using the stable Treelite version.

**Comment by hcho3** [comment]
This PR will be ready once #46 is merged.

**Comment by hcho3** [comment]
@wphicks Can you review this? Now we are able to natively ingest models from scikit-learn as well as cuML RF, without needing the Python interpreter.

**Comment by wphicks** [comment]
@hcho3 Yep, absolutely! This is very exciting. In addition to code-level review, let me add a test for this to #49 and run it through that as well, and then we'll get it merged.

**Comment by hcho3** [comment]
@wphicks Thanks!

FYI: When it comes to testing sklearn RF models, the output can be inexact due to the truncation of float64 split thresholds into float32 in FIL. (FIL uses float32, but sklearn RF uses float64) So you may want to relax the threshold for checking the correctness of the output, e.g. `np.testing.assert_almost_equal(result, expected_result, decimal=3)`.

**Comment by wphicks** [comment]
Going to go ahead and merge this as is because I don't want it to become too entangled with the CI/testing work. We'll add a test in a follow-on PR. See #54

**Pull request merged**
