### PR TITLE
fix "Dockerfile parse error line xx: Unknown flag: mount"

### PR DESCRIPTION
**Pull request by daxiongshu**
When I run `./build.sh`, I have this error: 
```
(base) jiweil@dgx11:~/rapids/fil_backend$ ./build.sh
[+] Building 0.1s (2/2) FINISHED
 => [internal] load .dockerignore                                                                                                                                                    
 => => transferring context: 103B                                                                                                                                        
 => [internal] load build definition from Dockerfile                                                                                                                  
 => => transferring dockerfile: 5.74kB                                                                                                                                                
failed to solve with frontend dockerfile.v0: failed to create LLB definition: Dockerfile parse error line 36: Unknown flag: mount
```
I googled and found a fix [here](https://github.com/docker/buildx/issues/348)

### CODE REVIEW

**Comment by wphicks** [comment]
Great! Thank you very much! It looks like from the [docs here](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md) that version 1.3 should be sufficient. Can you try `# syntax=docker/dockerfile:1.3` locally? If it works, it's probably better to keep to a stable version.

**Comment by daxiongshu** [comment]
> Great! Thank you very much! It looks like from the [docs here](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md) that version 1.3 should be sufficient. Can you try `# syntax=docker/dockerfile:1.3` locally? If it works, it's probably better to keep to a stable version.

yeah, it works. Thanks! :)

**Review by wphicks — APPROVED** [review]
LGTM!

**Comment by wphicks** [comment]
CI failure was unrelated; rerunning

**Pull request merged**
